[package]
name = "knapsac"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
prettytable-rs = "0.8.0"
dirs = "4.0.0"
